### ISSUE TITLE
[New Chat] - Scan new group feature missing

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#122] opened 2019-06-25 20:13 UTC
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cyBerta** [comment] 2019-09-18 17:13
@r10s @nayooti is #239 a duplicate of this ticket?

**Comment by r10s** [comment] 2019-09-18 17:37
i think so; to clearify: the scanners are always the same, the qr-code makes the difference, there are qr-codes for creating a 1:1 chat and qr-codes for joining a group.

**Closed by r10s** 2019-09-18 17:37 UTC
