### ISSUE TITLE
Release group for testflight / appstore

### ISSUE THREAD

**Issue by hpk42** [deltachat/deltachat-ios#63] opened 2019-05-06 08:35 UTC
next testflight release should be done by basti, and @cyberta and @jonasreinsch and @dignifiedquire should also be able to do a testflight release.  there is a merlinux account and maybe @Simon-Laux and @jonasreinsch can help to move towards this new release group. Or would it make sense to wait with this until we release to appstore?

**Comment by Simon-Laux** [comment] 2019-05-06 15:59
I would like to do the move as soon as possible so a new testflight release doesn't depend only on @jonasreinsch having time/being available. and everybody can publish a new test build. IMHO.
I can add you to the merlinux dev team, I only need your appleId's (we shouldn't exchange those publicly over github, though.)

**Comment by hpk42** [comment] 2019-05-07 20:55
if we release testflight under a new app id the question is
if we need to support https://github.com/deltachat/deltachat-ios/issues/64

it's maybe not neccessary but: if we later move to app store would
the testflight users retain their state when they move to appstore?

**Comment by Simon-Laux** [comment] 2019-05-07 21:09
I think they wouldn't retain the app state, we should provide export/import backup and a guide on how to do it for this use case.
We could also transfer ownership off the app from @jonasreinsch account to the merlinux account, but then the problem isn't solved -as one can't change bundle ids.

> the testflight users retain their state when they move to appstore?

As long as the bundle/app id is the same and the data has the same format migration beween testflight and appstore isn't normaly any problem, though we should recommend doing a backup, because apple also warns the user that the data might be incompatible and the user could feel a bit safer when they have a backup in case the migration doesn't work.

**Comment by hpk42** [comment] 2019-05-08 15:02
Had lunch with @jonasreinsch today -- it seems he could transfer the bundle id to the new account which would allow to do releases that can access the current DC-testflight-release' data.  The same would then be true when we move to appstore.  @jonasreinsch does anything speak against doing this transfer right now already?

**Comment by jonasreinsch** [comment] 2019-05-08 15:23
hm, it seems that only apps that are already released in the app store can be transferred.

This is how it looks for an app that is already on the app store:

![grafik](https://user-images.githubusercontent.com/144326/57386959-c171f100-71b5-11e9-91b5-9724cd3b120b.png)

And here it is for Delta Chat, which is only in TestFlight right now:
![grafik](https://user-images.githubusercontent.com/144326/57387123-07c75000-71b6-11e9-96f8-c73ebb2a11c6.png)

**Comment by Simon-Laux** [comment] 2019-05-08 15:59
May I ask how many testflight users we have right now?

**Comment by hpk42** [comment] 2019-05-16 10:37
@Simon-Laux could you help @nayooti to get ios release rights for the group account?   this is orthogonal to the export/import question, and thus also to the testflight user numbers.  Let's discuss that part rather in https://github.com/deltachat/deltachat-ios/issues/64 ... this issue is only about getting everybody setup so releases can happen.

**Comment by r10s** [comment] 2019-07-10 12:27
we can build our own testflight-releases now (and later store-releases). so, i think this can be closed.

**Closed by r10s** 2019-07-10 12:27 UTC
