### ISSUE TITLE
hanging when returning to the app

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#100] opened 2019-06-04 06:03 UTC
I am not sure where this come from, but when switching back and forth between apps, dc freezes the ui for a while when coming back

**Comment by nayooti** [comment] 2019-06-04 06:56
ok, interesting.  I'll check that out.

Thank you!

**Comment by nayooti** [comment] 2019-06-07 13:36
The bug doesn't appear on my pre-Rust build.

I get this error (on latest master) when bringing the app to the backgrond (home-button), swiping up, restart app.
It also doesn't show the launchscreen (dv violet with deltachat logo) when relaunching the app.

If this is rust-related, the fact that the launchscreen doesn't show up make me think that the app doesn't shut down properly. 
Maybe it relates to #90 ?

**Comment by r10s** [comment] 2019-08-15 22:31
also noticed that, however, with the "old" rust build from 2019-07-06 https://github.com/deltachat/deltachat-core-rust/commit/11eb86c77fd7c0cffa8ca466fcec975141683adf , will checkout the current master asap

**Comment by r10s** [comment] 2019-09-01 16:06
did not notice that again with the current rust master, btw.

**Comment by r10s** [comment] 2019-09-19 12:14
the bug is still there. i could reproduce that in the simulator by
1. swiping the running app away
2. re-opening the app

unfortunately, due to 1. the connection with the debugger is lost.

thinking over that with @hpk42 a bit, might be worth checking out if disabling the event handler makes a change. if so, we would know to have a closer look there.

**Comment by r10s** [comment] 2019-09-20 12:27
found a way to reproduce this on an iphone7:

start app from xcode -> double-home, swipe-app-away, home, control-center, enable-flightmode, start -> hang

**Comment by r10s** [comment] 2019-09-20 16:42
hm, meanwhile i have the feeling these are _two_ buts.

- the intially reported bug and **[way0]** is a hanging of a few seconds
- the **[way1]** but hangs for minutes - and is not reproducible _without_ a debugger (better than the other way round :)  
also, for [way1] i've seen drawing problems in the status bar, sth. as the text "LTE" overwritten by the text "Searching" - looks to me as if there is a static _image_ used to speed up start that is not removed or so - or lays over the real app. also @Simon-Laux had that idea (on mtd01 ;)

**Comment by r10s** [comment] 2019-09-29 20:05
maybe i found one issue:

dc_maybe_network() seems to hang on flaky/no network.

probably due to [`*context.probe_imap_network.write().unwrap() = true;`](https://github.com/deltachat/deltachat-core-rust/blob/master/src/job.rs#L586) which cannot acquire a write-lock for $reasons. not sure, though.

**Comment by r10s** [comment] 2019-10-01 18:22
not totally sure, but at least on my device, i have not seen hangs the last day (apart from hang no. 2 mentioned in https://github.com/deltachat/deltachat-core-rust/issues/651

**Comment by r10s** [comment] 2019-10-11 17:21
closing this is as the initial issue seems to be solved.

the remaining hang is less annoying and lives in issue https://github.com/deltachat/deltachat-ios/issues/342 now

**Closed by r10s** 2019-10-11 17:21 UTC
Labels: bug
