### ISSUE TITLE
Improve core wrapper: all init functions should throw errors on null pointers

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1628] opened 2022-07-02 17:13 UTC
To prevent bugs

**Comment by r10s** [comment] 2022-07-02 19:10
which kind of _concrete_ bugs would be prevented?

in general, core just handles NULL pointers gracefully, adding error handling to all callers of ”all init functions" would be quite some work and complicate code. so while maybe nice in theory, not sure if this is really practical. it would probably some effort for few impact.

note that the wrapper object will still exist with NULL pointers - however, all calls to it will be "blocked" by core. one cannot do "harm" in these NULL objects - so the error class of https://github.com/deltachat/deltachat-ios/issues/1504 is very likely unrelated as a "real" account is gone.

in case of dc_accounts_get(), this also unlikely to fail as the objects are all already in memory. similar for other wrappers, the NULL pointer may only happen when eg. a message was _just_ deleted - this is visible eg. in ui by an empty entry or so then.

nb: all that works similar on android and maybe also on desktop.

not saying, that this cannot be done _differently_, however :)

**Comment by Simon-Laux** [comment] 2022-07-02 19:28
> however, all calls to it will be "blocked" by core

or return wrong values: for example in `dc_is_configured` 0 is error and a return value in one.

Or take this example:
```swift
    public func getSelected() -> DcContext {
        let cPtr = dc_accounts_get_selected_account(accountsPointer)
        return DcContext(contextPointer: cPtr, logger: logger)
    }
```

If `dc_accounts_get_selected_account` fails, we trick swift into giving us a useless wrapper anyway? why not fail fast?

**Comment by r10s** [comment] 2022-07-02 19:38
> or return wrong values: for example in dc_is_configured 0 is error and a return value in one.

that's true - but still not really an issue as one is working with an "virtual NULL object".

> If dc_accounts_get_selected_account fails, we trick swift into giving us a useless wrapper anyway? why not fail fast?

all these functions have no network involved, in case of get_selected_account not even memory, so failure is very unlikely at all.

however, i am not against changing it, esp, for the dc_account_t that is probably not uses at so many places. as said, things can be done differently and maybe better.  
but i doubt, it is the cause of errors as discussed initially. the time is probably spend better in checking for the real cause.

**Comment by r10s** [comment] 2022-07-04 18:47
as bespoken, let's close this. we can improve as needed if there is some concrete thing that is targeted then.

**Closed by r10s** 2022-07-04 18:47 UTC
Labels: discussion
