### ISSUE TITLE
Weird scroll-animation/jumps in Chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2232] opened 2024-07-11 13:40 UTC
sometimes, there is some unneeded scrolling of the message list:

instead of just shifting the view some pixels up in case of a new message,
scrolling takes place from the very top to the bottom.

this issue is pretty old,  but here is a way to get a reproducible comparison with correct scrolling:

- open a filled the "Saved Messages" chat
- send a first short message "s1" -> scrolling is fine, just a few pixels up
- send a second short message "s2" -> scrolling from very top to the bottom, same for subsequent messages from the same device

leave the "Saved Messages" chat open, but now send a message **from another device:**

- messages "o1", "o2" -> scrolling is fine, just a few pixels up
- from same device, "s3", again -> scrolling from very top to the bottom

so, question is, what is the difference between **wrong s2, s3** and **fine s1, o1, o2**

https://github.com/deltachat/deltachat-ios/assets/9800740/5fb88c9d-578c-4eb8-bbdd-0cbd17a7209b

(ignore the flickering scroll down button, [see here](https://github.com/deltachat/deltachat-ios/pull/2231#pullrequestreview-2171522134))

-------

Note to self:

```swift
let messageId = ui["message_id"] as? Int ?? 0
if messageId > 0 {
    let msg = self.dcContext.getMessage(id: messageId)
```

**Comment by feld** [comment] 2024-09-27 01:02
This looks like it was supposed to be fixed in 1.46.8 but it is very much persisting. It still has jumpy-ness and it's very annoying how it will never scroll to bottom automatically like when you're sending multiple consecutive messages in a chat

**Comment by zeitschlag** [comment] 2024-10-10 14:08
Note to self:

It's `messageInputBar.inputTextView.becomeFirstResponder()` in `ChatViewController.focusInputTextView()` that makes everything flicker and jump.

**Comment by Amzd** [comment] 2024-10-11 08:36
This is caused by the textView being removed from superview and re-added when `ChatViewController.configureDraftArea` is called, and can be fixed by adding `guard view !== middleContentView else { return }` in `InputBarAccessoryView.setMiddleContentView`. I will fix this in a PR probably this weekend.

I am rewriting the `ChatViewController` to have its tableView flipped which means we need to do way less scrolling tricks because scroll views by default scroll up when a cell is added, so when flipped it will scroll down when a cell is added.

**Comment by r10s** [comment] 2024-10-11 14:34
>  I will fix this in a PR probably this weekend.

that'd be very welcome - we're struggling with that quite a while without really getting a grip on it. really looking forward and curious about the details 🤩

**Closed** 2024-10-15 08:29 UTC
Labels: bug

**Comment by r10s** [comment] 2024-10-15 09:52
very nice to have this fixed! 👌
this is a very old bug (much oder  than this issue :)
