### ISSUE TITLE
rust compile error

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#497] opened 2020-01-15 16:39 UTC
when trying to compile latest master, i get the following error (beta22 works):

```
Showing Recent Messages
   Compiling deltachat v1.0.0-beta.22 (/Users/bpetersen/projects/deltachat-ios/deltachat-ios/libraries/deltachat-core-rust)

error[E0433]: failed to resolve: could not find `blocking` in `reqwest`

  --> src/configure/read_url.rs:14:20

   |

14 |     match reqwest::blocking::Client::new()

   |                    ^^^^^^^^ could not find `blocking` in `reqwest`



error[E0433]: failed to resolve: could not find `blocking` in `reqwest`

   --> src/oauth2.rs:157:33

    |

157 |         let response = reqwest::blocking::Client::new()

    |                                 ^^^^^^^^ could not find `blocking` in `reqwest`



error[E0433]: failed to resolve: could not find `blocking` in `reqwest`

   --> src/oauth2.rs:294:33

    |

294 |         let response = reqwest::blocking::Client::new().get(&userinfo_url).send();

    |                                 ^^^^^^^^ could not find `blocking` in `reqwest`



aborting due to 3 previous errors



For more information about this error, try `rustc --explain E0433`.
```

**Comment by r10s** [comment] 2020-01-15 17:21
tried `rustup update` , `cargo update`  and cleaning the build dir using ./tools/clean-core.sh - did not help

**Comment by r10s** [comment] 2020-01-15 17:22
android seems to build fine on the same machine (2 targets ready up to now, still building)

**Comment by link2xt** [comment] 2020-01-17 08:27
The problem is probably `--no-default-features` in this line:

https://github.com/deltachat/deltachat-ios/blob/f6686f252f74750b4f3def5ac97b4bffeda3f218/deltachat-ios.xcodeproj/project.pbxproj#L1028

I have opened https://github.com/deltachat/deltachat-core-rust/pull/1184, it should fix this bug probably, but I am not sure why do you want to disable vendored sqlite ("bundled" feature) for iOS.

**Comment by r10s** [comment] 2020-01-17 10:56
it works with the fix :)

wrt the `--no-default-features` i have no idea, @dignifiedquire did the complicated rust bootstrapping that time, and i would not change a running system :)

**Comment by link2xt** [comment] 2020-01-17 13:07
Closed in https://github.com/deltachat/deltachat-core-rust/pull/1184

**Closed by link2xt** 2020-01-17 13:07 UTC
Labels: bug, build
