### ISSUE TITLE
UISearchDisplayController is no longer supported

### ISSUE THREAD

**Issue by grossbart** [deltachat/deltachat-ios#487] opened 2020-01-11 13:47 UTC
- Device: iPhone X
- iOS version: 13.3
- Delta Chat version: 1.0.2

### Expected behavior

I shook the phone to view the debug window and then was browsing around the various sections.

### Actual behavior

Delta Chat crashes immediately when I try to access the "Network" page.

### Steps to reproduce the problem

1. Shake phone to view debug view
2. Click on "Network" link
3. Crash

## Screenshots

![screenshot](https://user-images.githubusercontent.com/10811/72205237-01921d80-3481-11ea-9073-42b0e9e9cc14.jpg)

### Logs

```
Details:
Name: NSGenericException
Date: 11.01.2020, 14:36:16
Reason: UISearchDisplayController is no longer supported when linking against this version of iOS. Please migrate your application to UISearchController.
Stack trace:
0 CoreFoundation 0x000000018bcd2a5c 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 1227356
1 libobjc.A.dylib 0x000000018b9f9fa4 objc_exception_throw + 56
2 CoreFoundation 0x000000018bbc81c0 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 135616
3 UIKitCore 0x000000018f6de7e8 UISearchDisplayControllerNoLongerSupported + 248
4 UIKitCore 0x000000018f6deab8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 3787448
5 UIFoundation 0x000000018f2cd39c A482604C-C34A-3110-8C19-9724FB7334F4 + 443292
6 UIFoundation 0x000000018f2cd5d0 A482604C-C34A-3110-8C19-9724FB7334F4 + 443856
7 UIFoundation 0x000000018f269ac8 A482604C-C34A-3110-8C19-9724FB7334F4 + 35528
8 UIKitCore 0x000000018f725f88 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 4079496
9 UIKitCore 0x000000018f9e5898 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 6961304
10 UIFoundation 0x000000018f2cd39c A482604C-C34A-3110-8C19-9724FB7334F4 + 443292
11 UIFoundation 0x000000018f269ac8 A482604C-C34A-3110-8C19-9724FB7334F4 + 35528
12 UIKitCore 0x000000018f9e98bc 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 6977724
13 UIFoundation 0x000000018f2cd39c A482604C-C34A-3110-8C19-9724FB7334F4 + 443292
14 UIFoundation 0x000000018f2cd5d0 A482604C-C34A-3110-8C19-9724FB7334F4 + 443856
15 UIFoundation 0x000000018f269ac8 A482604C-C34A-3110-8C19-9724FB7334F4 + 35528
16 UIKitCore 0x000000018f9e4934 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 6957364
17 UIKitCore 0x000000018f9e7524 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 6968612
18 UIKitCore 0x000000018fe9a224 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 11895332
19 UIKitCore 0x000000018fe9a0b8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 11894968
20 UIKitCore 0x000000018fe9ae68 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 11898472
21 UIKitCore 0x000000018fe9b0ac 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 11899052
22 UIKitCore 0x000000018fe9b39c 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 11899804
23 UIKitCore 0x000000018ff0fc6c 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 12377196
24 UIKitCore 0x000000018ff0f7e8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 12376040
25 UIKitCore 0x000000018ff0fee8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 12377832
26 UIKitCore 0x000000018fd4f128 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10539304
27 UIKitCore 0x000000018fd3ec78 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10472568
28 UIKitCore 0x000000018fd6eac8 27D3041D-A1DE-3C3A-8DC0-994B5982DC49 + 10668744
29 CoreFoundation 0x000000018bc4fe68 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 691816
30 CoreFoundation 0x000000018bc4ad54 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 671060
31 CoreFoundation 0x000000018bc4b320 1B9B1E61-8CB4-3903-9870-402C3DE959BB + 672544
32 CoreFoundation 0x000000018bc4aadc CFRunLoopRunSpecific + 464
33 GraphicsServices 0x0000000195bd0328 GSEventRunModal + 104
34 UIKitCore 0x000000018fd45ae0 UIApplicationMain + 1936
35 deltachat-ios 0x0000000102bf23b0 deltachat-ios + 25520
36 libdyld.dylib 0x000000018bad4360 2E3F4750-8B67-398B-8530-8417651B1718 + 4960
```

**Comment by r10s** [comment] 2020-01-11 15:30
@grossbart thanks for the info :)

i think this is a duplicate of https://github.com/deltachat/deltachat-ios/issues/479

**Closed by r10s** 2020-01-11 15:30 UTC
Labels: duplicate
