### ISSUE TITLE
invite links should open in-app

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2279] opened 2024-08-20 13:42 UTC
when tapping an invite link (`http://i.delta.chat...`) inside delta chat, not the browser should be opened by the action should be done directly within delta chat

-----

## Notes to self

- associated domain is set and also `https://i.delta.chat/.well-known/apple-app-site-association` looks correct (also: Banner appears)

**Comment by zeitschlag** [comment] 2024-09-03 09:36
Just noticed that this is a duplicate of #2134

**Closed by zeitschlag** 2024-09-03 09:36 UTC
Labels: enhancement
