### ISSUE TITLE
badge counter on app icon not displayed sometimes

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#626] opened 2020-04-10 13:08 UTC
Expected: 
The app icon should show a red badge with the number of unread messages like other messaging apps.

**Comment by webratte** [comment] 2020-04-10 15:29
Please the same for Android 😜

**Comment by r10s** [comment] 2020-04-11 00:31
it should be there on ios.

**Comment by Simon-Laux** [comment] 2020-04-11 06:41
Then it’s a bug, because it is not there on the AppStore version.

**Comment by r10s** [comment] 2020-04-11 09:49
k, thanks for coming back, we can reopen this.

however, it seems to be a bit more special, in general, eg. on my devices, it is there.

**Comment by r10s** [comment] 2020-04-11 10:29
nb: this is the corresponding property: [UIApplication. applicationIconBadgeNumber ](https://developer.apple.com/documentation/uikit/uiapplication/1622918-applicationiconbadgenumber) - at a first glance, it is updated when a chat is opened or when new messages arrive.

**Comment by r10s** [comment] 2020-04-11 11:00
@Simon-Laux which device are you using? i noticed a bug in the emulator: when when setting the counter manually and independently of the core eg. to `123`, when pressing "home", the badge counter disappears sometimes. it reappears when swiping the apple-launcher left or right. this happens even if Delta Chat is not even running (the counter is remembered). might be that the system is confused with some chanced values. bugs everywhere :)

i could not reproduce this on "real" devices with ios 13, however.

**Comment by r10s** [comment] 2020-08-03 15:54
i do not think this is an issue any longer, closing for now. please reopen a new issue with updated details if this is still an issue.

**Closed by r10s** 2020-08-03 15:54 UTC
Labels: bug, needs-retry
