### ISSUE TITLE
Failed to parse fingerprint in QR code

### ISSUE THREAD

**Issue by mchekalov** [deltachat/deltachat-ios#808] opened 2020-06-22 12:07 UTC
- Operating System - iOS
- Delta Chat Version: 1.9.5(37)

1) Create new group
2) Take QR-code of this group.
3) Scan it with Iphone Cam
![1](https://user-images.githubusercontent.com/2028869/85285746-1d6f0600-b49a-11ea-97de-6ca1d96b9ae9.PNG)
![2](https://user-images.githubusercontent.com/2028869/85285754-2069f680-b49a-11ea-86c5-4be37ff9367e.PNG)

**Comment by r10s** [comment] 2020-06-22 13:24
hi, @mchekalov - thanks for reporting!

the issue is fixed with https://github.com/deltachat/deltachat-core-rust/pull/1631 and the fix will be available with the next release, coming these days :)

**Closed by r10s** 2020-06-22 13:24 UTC
Labels: bug
