### ISSUE TITLE
DeltaChat messages are kept in infolder

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-ios#1255] opened 2021-06-08 07:29 UTC
- Device:  iOS 14.4.2 on an iPhone 8
- iOS version: iOS 14.4.2
- Delta Chat version: 1.20.2
- Expected behavior: DeltaChat messages are moved to the DeltaChat folder and shown in the app
- Actual behavior: Some DeltaChat messages are not moved, but kept in the infolder. Thus they are not shown in the DeltaChat app. And when opening the e-mail app the user sees an unreadable message. And on a computer Thunderbird shows: Encrypted message and you don't have the key (my translation)
- Steps to reproduce the problem: receive some messages
- Screenshots:
- Logs: to late for that. Only later events are shown in the log.

Several subsequent attempts to send DeltaChat messages with an image attachment from an Android device to this device didn't work. Finally, a message without attachment was received as expected.

**Comment by cyBerta** [comment] 2021-06-08 12:31
@havet thanks for reporting. You are using Outlook as your email provider? I remember there have been issues with outlook stripping some headers for outgoing messages, but I remember vaguely that some $things have been done wrt that problem (https://github.com/deltachat/deltachat-core-rust/issues/1006). 

Do you use on both devices, Android and iOS 2 different Outlook email accounts? 
Can you send messages with images from the iOS device to Android? 

For now it is still a little bit hard to pin down the root cause to the described issue.

**Comment by havet** [comment] 2021-06-08 14:06
Hi,
1) no, I meant the e-mail client, but it was a misunderstanding. The receiver uses Thunderbird.
2) Yes, we have are own e-mail accounts (not Outlook).
3) Yes, the receiver can send images to me.
I will update the issue as needed.

**Comment by havet** [comment] 2021-06-08 14:12
Today I've sent two images with DeltaChat and they where properly received as expected.

**Comment by havet** [comment] 2021-06-10 07:26
How is DeltaChat actually working? Is there some "time restriction" making DC looking just for "new" messages in the in-folder? In that case this problem might occur if the check of the inbox is disturbed somehow. Next time DC checks the inbox it would ignore messages older than the current time. 

1. Can anyone confirm or refute this?
2. If this is true a change of the behaviour of DeltaChat is needed. DC must check for older messages if not everytime, at least e.g. each 5 times or something like that.

**Comment by havet** [comment] 2021-06-14 18:41
Now I've checked the receivers mail account. The missing mail is NOT left in the inbox. The inbox contains copies of old DeltaChat-messages that I found in the receivers DeltaChat-folder and are shown in the receivers DeltaChat-app (iOS).

The receiver has NOT got my message from my Android-phone - it's not in the inbox and not in the DeltaChat-folder. So The issues are NOT related.

**Comment by cyBerta** [comment] 2021-06-16 06:40
> Is there some "time restriction" making DC looking just for "new" messages in the in-folder?

No, there are no time restrictions for new messages in the inbox-folder

**Comment by cyBerta** [comment] 2021-06-16 07:01
> The inbox contains copies of old DeltaChat-messages that I found in the receivers DeltaChat-folder and are shown in the receivers DeltaChat-app (iOS).

@r10s @link2xt this might be a core issue. Could you tell us if messages are copied and not moved from inbox to the DeltaChat folder? These clean-up jobs are done on a regular basis, right? 


> The receiver has NOT got my message from my Android-phone - it's not in the inbox and not in the DeltaChat-folder. So The issues are NOT related.

That means at least on iOS everything worked as intended. No incoming message - no message shown in DC iOS.

**Comment by havet** [comment] 2021-06-16 10:56
Normally the messages are moved to the DC Folder. I don't know why these messages have been copied, but not moved.
Maybe some kind of interruption? DC interrupted? Failure at the e-mail server? Temporary network problem? 
Anyhow : DeltaChat should not leave any messages in the inbox. Failures must be corrected afterwards. 

I think this happened:
1) DC checks the in-folder and finds a message to move to the DeltaChat-folder.
2) Moving consists of two steps: first copy to the new location and the remove from the old location. The first step worked OK, but then the process was interrupted somehow: the message was copied to the DeltaChat-folder, but it was not deleted in the in-folder.
3) Next time DC checks the in-folder it finds the message, but it is ignored because it has already been copied to the DeltaChat-folder. (This is NOT the expected behavior!)

Expected behavior:
1. DC finds out that the message in the in-folder is identical to a message already present in the DeltaChat-folder.
2. DC deletes the copy present in the in-folder. No DeltaChat-messages are ever left in the in-folder.

**Comment by link2xt** [comment] 2021-06-16 11:26
> Could you tell us if messages are copied and not moved from inbox to the DeltaChat folder?

This happens if the server does not support `MOVE` (or supports it but does not advertise this capability).

There is a problem in the core that DC only tracks one UID per message, instead of all of them, and may forget about some copies if it is interrupted between COPY and DELETE or in more complex multi-device cases: https://github.com/deltachat/deltachat-core-rust/issues/1334

**Comment by r10s** [comment] 2021-12-01 13:46
closing as there are more concrete core issues and ios cannot do much on that anyway.

**Closed by r10s** 2021-12-01 13:46 UTC
